<?php
$translate = $this->plugin('translate');
?>
<nav class="pagination" role="navigation">
<?php if ($totalCount): ?>
    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
        <span>Página</span>
        <input type="text" name="page" class="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Página'); ?>">
        <span class="page-count"><?php echo sprintf($translate('de %s'), $pageCount); ?></span>
    </form>

    <?php if ($currentPage != 1): ?>
    <?php echo $this->hyperlink('', $previousPageUrl, ['class' => 'previous explore-left button', 'title' => $translate('Anterior'), 'aria-label' => $translate('Anterior')]); ?>
    <?php else: ?>
    <span class="previous explore-left button inactive"></span>
    <?php endif; ?>

    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink('', $nextPageUrl, ['class' => 'next explore-right button', 'title' => $translate('Siguiente'), 'aria-label' => $translate('Siguiente')]); ?>
    <?php else: ?>
    <span class="next explore-right button inactive"></span>
    <?php endif; ?>
    
        <span class="row-count"><?php if ($totalCount > 1): ?><?php echo sprintf('%s resultados', $totalCount); ?><?php else: ?><?php echo sprintf('%s resultado', $totalCount); ?><?php endif; ?></span>
<?php else: ?>
    <?php echo '<div class="cero-resultados">Ningún resultado</div>'; ?>
<?php endif; ?>
</nav>


