<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form">
    <input type="text" title='Cadena de búsqueda' name="fulltext_search" value="<?php echo $searchValue; ?>" placeholder="<?php echo $translate('buscar...'); ?>">
    <button type="submit" alt="search" title="Buscar"><?php echo 'BUSCAR'; ?></button>
</form>
